"use client";
import "./globals.css";
import { PropsWithChildren, useEffect } from "react";
import { usePathname } from "next/navigation";
import { Header } from "@/components/Header/Header";
import { Providers } from "@/store/Provider";

export default function RootLayout({ children }: PropsWithChildren<{}>) {
  const router = usePathname();

  const showHeader = router === "/Home" ? true : false;

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body suppressHydrationWarning={true}>
        <Providers>
          {showHeader && <Header />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
